# Use uma imagem base do Node.js
FROM node:16

# Defina o diretório de trabalho no container
WORKDIR /app

# Copie os arquivos de dependências
COPY package*.json ./

# Instale as dependências
RUN npm install

# Copie o restante do código
COPY . .

# Exponha a porta usada pelo servidor
EXPOSE 5000

# Comando para iniciar o servidor
CMD ["npm", "start"]
