# Use uma imagem base do Node.js para build
FROM node:16 as build

# Defina o diretório de trabalho
WORKDIR /app

# Copie os arquivos de dependências
COPY package*.json ./

# Instale as dependências
RUN npm install

# Copie o restante do código e faça o build
COPY . .
RUN npm run build

# Use uma imagem base do Nginx para servir os arquivos estáticos
FROM nginx:alpine

# Copie os arquivos do build para a pasta padrão do Nginx
COPY --from=build /app/build /usr/share/nginx/html

# Exponha a porta usada pelo Nginx
EXPOSE 80

# Comando padrão para rodar o Nginx
CMD ["nginx", "-g", "daemon off;"]
